var nodes = [
	{id: 0, label: '0', color: '#FF7F32'},
	{id: 1, label: '1', color: '#5C6670'},
	{id: 2, label: '2', color: '#5C6670'},
	{id: 3, label: '3', color: '#5C6670'},
	{id: 4, label: '4', color: '#5C6670'},
	{id: 5, label: '5', color: '#5C6670'},
	{id: 6, label: '6', color: '#5C6670'},
	{id: 7, label: '7', color: '#5C6670'},
	{id: 8, label: '8', color: {background:'#78BE20', border:'green'}},
	{id: 9, label: '9', color: '#5C6670'},
	{id: 10, label: '10', color: {background:'#78BE20', border:'green'}},
	{id: 11, label: '11', color: {background:'#78BE20', border:'green'}},
	{id: 12, label: '12', color: '#5C6670'},
	{id: 13, label: '13', color: '#5C6670'},
	{id: 14, label: '14', color: '#5C6670'},
	{id: 15, label: '15', color: '#5C6670'},
	{id: 16, label: '16', color: '#5C6670'},
	{id: 17, label: '17', color: '#5C6670'},
	{id: 18, label: '18', color: '#5C6670'},
	{id: 19, label: '19', color: '#5C6670'},
	{id: 20, label: '20', color: '#5C6670'},
	{id: 21, label: '21', color: '#5C6670'},
	{id: 22, label: '22', color: '#5C6670'},
	{id: 23, label: '23', color: '#5C6670'},
	{id: 24, label: '24', color: '#5C6670'},
	{id: 25, label: '25', color: '#5C6670'},
	{id: 26, label: '26', color: '#5C6670'},
	{id: 27, label: '27', color: '#5C6670'},
	{id: 28, label: '28', color: '#5C6670'},
	{id: 29, label: '29', color: '#5C6670'},
	{id: 30, label: '30', color: '#5C6670'},
	{id: 31, label: '31', color: '#5C6670'},
	{id: 32, label: '32', color: {background:'#78BE20', border:'green'}},
	{id: 33, label: '33', color: '#5C6670'},
	{id: 34, label: '34', color: {background:'#78BE20', border:'green'}},
	{id: 35, label: '35', color: {background:'#78BE20', border:'green'}},
	{id: 36, label: '36', color: '#5C6670'},
	{id: 37, label: '37', color: '#5C6670'},
	{id: 38, label: '38', color: '#5C6670'},
	{id: 39, label: '39', color: '#5C6670'},
	{id: 40, label: '40', color: '#5C6670'},
	{id: 41, label: '41', color: '#5C6670'}
];

var edges = [
	{from: 0, to:7, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 0, to:14, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 1, to:7, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 1, to:15, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 2, to:10, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 2, to:15, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 3, to:9, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 3, to:15, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 4, to:11, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 4, to:14, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 5, to:11, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 5, to:14, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 6, to:7, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 6, to:8, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 7, to:7, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 7, to:9, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 8, to:10, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 8, to:9, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 9, to:9, arrows:'to', label: 'a, b', font: {align: 'top'}},
	{from: 10, to:11, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 10, to:8, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 11, to:11, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 11, to:8, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 12, to:19, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 12, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 13, to:19, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 13, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 14, to:22, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 14, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 15, to:21, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 15, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 16, to:23, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 16, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 17, to:23, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 17, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 18, to:19, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 18, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 19, to:19, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 19, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 20, to:22, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 20, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 21, to:21, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 21, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 22, to:23, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 22, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 23, to:23, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 23, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 24, to:37, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 24, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 25, to:37, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 25, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 26, to:40, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 26, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 27, to:39, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 27, to:27, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 28, to:41, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 28, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 29, to:41, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 29, to:26, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 30, to:31, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 30, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 31, to:31, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 31, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 32, to:34, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 32, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 33, to:33, arrows:'to', label: 'a, b', font: {align: 'top'}},
	{from: 34, to:35, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 34, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 35, to:35, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 35, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 36, to:37, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 36, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 37, to:37, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 37, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 38, to:40, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 38, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 39, to:39, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 39, to:33, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 40, to:41, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 40, to:32, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 41, to:41, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 41, to:32, arrows:'to', label: 'b', font: {align: 'top'}}
];