var nodes = [
	{id: 0, label: '0', color: '#FF7F32'},
	{id: 1, label: '1', color: '#5C6670'},
	{id: 2, label: '2', color: '#5C6670'},
	{id: 3, label: '3', color: '#5C6670'},
	{id: 4, label: '4', color: '#5C6670'},
	{id: 5, label: '5', color: '#5C6670'},
	{id: 6, label: '6', color: '#5C6670'},
	{id: 7, label: '7', color: '#5C6670'},
	{id: 8, label: '8', color: '#5C6670'},
	{id: 9, label: '9', color: {background:'#78BE20', border:'green'}},
	{id: 10, label: '10', color: '#5C6670'},
	{id: 11, label: '11', color: '#5C6670'},
	{id: 12, label: '12', color: '#5C6670'},
	{id: 13, label: '13', color: '#5C6670'},
	{id: 14, label: '14', color: '#5C6670'},
	{id: 15, label: '15', color: '#5C6670'},
	{id: 16, label: '16', color: '#5C6670'},
	{id: 17, label: '17', color: '#5C6670'},
	{id: 18, label: '18', color: '#5C6670'},
	{id: 19, label: '19', color: '#5C6670'},
	{id: 20, label: '20', color: '#5C6670'},
	{id: 21, label: '21', color: '#5C6670'},
	{id: 22, label: '22', color: '#5C6670'},
	{id: 23, label: '23', color: '#5C6670'},
	{id: 24, label: '24', color: '#5C6670'},
	{id: 25, label: '25', color: '#5C6670'},
	{id: 26, label: '26', color: '#5C6670'}
];

var edges = [
	{from: 0, to:10, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 0, to:2, arrows:'to', label: 'b, c, d, e, f', font: {align: 'top'}},
	{from: 0, to:12, arrows:'to', label: 'g', font: {align: 'top'}},
	{from: 1, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 1, to:0, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 1, to:4, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 1, to:2, arrows:'to', label: 'd, e, f', font: {align: 'top'}},
	{from: 2, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 2, to:2, arrows:'to', label: 'b, c, d, e, f', font: {align: 'top'}},
	{from: 3, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 3, to:2, arrows:'to', label: 'b, d, e, f', font: {align: 'top'}},
	{from: 3, to:5, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 4, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 4, to:0, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 4, to:2, arrows:'to', label: 'c, e, f', font: {align: 'top'}},
	{from: 4, to:6, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 5, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 5, to:0, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 5, to:2, arrows:'to', label: 'c, e, f', font: {align: 'top'}},
	{from: 5, to:6, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 6, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 6, to:2, arrows:'to', label: 'b, c, d, f', font: {align: 'top'}},
	{from: 6, to:7, arrows:'to', label: 'e', font: {align: 'top'}},
	{from: 7, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 7, to:2, arrows:'to', label: 'b, c, d, e', font: {align: 'top'}},
	{from: 7, to:8, arrows:'to', label: 'f', font: {align: 'top'}},
	{from: 8, to:11, arrows:'to', label: 'a, g', font: {align: 'top'}},
	{from: 8, to:0, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 8, to:2, arrows:'to', label: 'c, d, e, f', font: {align: 'top'}},
	{from: 9, to:10, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 9, to:20, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 9, to:11, arrows:'to', label: 'c, d, e, f', font: {align: 'top'}},
	{from: 9, to:12, arrows:'to', label: 'g', font: {align: 'top'}},
	{from: 10, to:11, arrows:'to', label: 'a, d, e, f, g', font: {align: 'top'}},
	{from: 10, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 10, to:13, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 11, to:11, arrows:'to', label: 'a, c, d, e, f, g', font: {align: 'top'}},
	{from: 11, to:20, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 12, to:11, arrows:'to', label: 'a, d, e, f, g', font: {align: 'top'}},
	{from: 12, to:20, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 12, to:14, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 13, to:11, arrows:'to', label: 'a, c, e, f, g', font: {align: 'top'}},
	{from: 13, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 13, to:15, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 14, to:11, arrows:'to', label: 'a, c, e, f, g', font: {align: 'top'}},
	{from: 14, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 14, to:15, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 15, to:11, arrows:'to', label: 'a, c, d, f, g', font: {align: 'top'}},
	{from: 15, to:20, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 15, to:16, arrows:'to', label: 'e', font: {align: 'top'}},
	{from: 16, to:11, arrows:'to', label: 'a, c, d, e, g', font: {align: 'top'}},
	{from: 16, to:20, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 16, to:17, arrows:'to', label: 'f', font: {align: 'top'}},
	{from: 17, to:11, arrows:'to', label: 'a, c, d, e, f, g', font: {align: 'top'}},
	{from: 17, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 18, to:19, arrows:'to', label: 'a', font: {align: 'top'}},
	{from: 18, to:20, arrows:'to', label: 'b, c, d, e, f', font: {align: 'top'}},
	{from: 18, to:21, arrows:'to', label: 'g', font: {align: 'top'}},
	{from: 19, to:20, arrows:'to', label: 'a, d, e, f, g', font: {align: 'top'}},
	{from: 19, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 19, to:22, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 20, to:20, arrows:'to', label: 'a, b, c, d, e, f, g', font: {align: 'top'}},
	{from: 21, to:20, arrows:'to', label: 'a, b, d, e, f, g', font: {align: 'top'}},
	{from: 21, to:23, arrows:'to', label: 'c', font: {align: 'top'}},
	{from: 22, to:20, arrows:'to', label: 'a, c, e, f, g', font: {align: 'top'}},
	{from: 22, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 22, to:24, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 23, to:20, arrows:'to', label: 'a, c, e, f, g', font: {align: 'top'}},
	{from: 23, to:18, arrows:'to', label: 'b', font: {align: 'top'}},
	{from: 23, to:24, arrows:'to', label: 'd', font: {align: 'top'}},
	{from: 24, to:20, arrows:'to', label: 'a, b, c, d, f, g', font: {align: 'top'}},
	{from: 24, to:25, arrows:'to', label: 'e', font: {align: 'top'}},
	{from: 25, to:20, arrows:'to', label: 'a, b, c, d, e, g', font: {align: 'top'}},
	{from: 25, to:26, arrows:'to', label: 'f', font: {align: 'top'}},
	{from: 26, to:20, arrows:'to', label: 'a, c, d, e, f, g', font: {align: 'top'}},
	{from: 26, to:18, arrows:'to', label: 'b', font: {align: 'top'}}
];